version: '3'
services:
 docker-app:
    image: catalogo-musical-api-compose:latest
    ports:
      - "8084:8084"
    depends_on:
      - docker-postgres
 docker-postgres:
    image: postgres:10.4
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
 docker-frontend:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /home/gustavo/dev/workspace-coder/catalogo-musical/dist/catalogo-musical:/usr/share/nginx/html
    depends_on:
      - docker-app
 docker-pgadmin:
    image: dpage/pgadmin4
    ports:
      - "15432:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=gustavocontabeis@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=PgAdmin2018!
    depends_on:
      - docker-postgres